language: clojure
lein: lein2
before_install:
  - npm install karma
jdk:
  - openjdk7
  - oraclejdk7
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - lein2 midje
  - lein2 cljsbuild once karma
  - karma start --single-run --browsers Firefox
