#!/bin/sh

set -e

echo "Building warden... "

lein with-profile release \
  do \
    clean, \
    aggravate, \
    cljx once, \
    cljsbuild clean release, \
    cljsbuild once release, \
    ring uberjar

echo "All done!"
