# meant for use with https://github.com/eggsby/ansible-supervise
# this playbook won't work in most environments
# it should however give you an idea of how to deploy the thing :)

- hosts: warden

  sudo: yes
  sudo_user: '{{ ansible_sudo_user }}'

  vars:
    app_home: '~/apps/warden'
    warden_jar: '{{ app_home }}/warden.jar'
    warden_version: '0.0.1-SNAPSHOT'

  pre_tasks:
    - name: fetching warden from maven repository
      nexus: >
        repo={{ maven.release_repo }}
        group_id=eggsby
        artifact_id=warden
        version={{ version}}
        filename=warden-{{ warden_version }}-standalone.jar
        dest={{ warden_jar }}

    - name: installing warden configuration
      template: src=warden.yaml.j2 dest={{ app_home }}/warden.yaml

  roles:
    - role: supervise
      name: warden
      supervisor_http: on
      command: java -jar {{ warden_jar }}
      app_env:
        port: '{{ warden_port }}'

  tasks:
    - name: restarting warden
      supervisorctl: name=warden state=restarted {{ super_args }}
