# meant for use with https://github.com/eggsby/ansible-supervise
# as is it is like this playbook won't work in most environments
# it should however give you an idea of how to deploy the thing :)

- hosts: warden

  sudo: '{{ sudo_user is defined }}'
  sudo_user: '{{ sudo_user|default(None) }}'

  vars:
    app_home: '~/apps/warden'
    warden_jar: '{{ app_home }}/warden.jar'
    warden_version: '0.0.1-SNAPSHOT'
    port: 3000

  pre_tasks:
    - nexus: >
        repo={{ maven.release_repo }}
        group_id=eggsby
        artifact_id=warden
        version={{ version}}
        filename=warden-{{ warden_version }}-standalone.jar
        dest={{ warden_jar }}

    - template: src=warden.yaml.j2 dest={{ app_home }}/warden.yaml

  roles:
    - role: supervise
      supervisor_http: on
      command: java -jar {{ warden_jar }}
      app_env:
        port: '{{ port }}'
