# meant for use with https://github.com/eggsby/ansible-supervise
- hosts: warden

  sudo: '{{ sudo_user is defined }}'
  sudo_user: '{{ sudo_user|default(None) }}'

  vars:
    app_home: '~/apps/warden'
    build_jar: '{{ playbook_dir }}/../target/warden-{{ version }}-standalone.jar'
    warden_jar: '{{ app_home }}/warden.jar'
    version: '0.0.1-SNAPSHOT'

  pre_tasks:
    - copy: src={{ build_jar }} dest={{ warden_jar }}

  roles:
    - role: supervise
      supervisor_http: on
      command: java -jar {{ warden_jar }}
